In [1]:
import numpy as np
import pickle

In [2]:
output_3d = None
output_2d = None

with open("outputs/open_arms_2d", "rb") as f:
    output_2d = pickle.load(f)
with open("outputs/open_arms_3d", "rb") as f:
    output_3d = pickle.load(f)

#### Explanation of general Structure

In [3]:
output_2d.shape

(1, 58)

In [4]:
output_2d

array([[ 4.6800000e+02,  2.0400000e+02,  9.4679272e-01,  4.6800000e+02,
         8.4000000e+01,  7.9522622e-01, -1.0000000e+00, -1.0000000e+00,
        -1.0000000e+00,  5.5600000e+02,  2.0400000e+02,  9.0535182e-01,
         6.9200000e+02,  2.3600000e+02,  9.7329307e-01,  8.2000000e+02,
         2.1200000e+02,  9.2068040e-01,  5.3200000e+02,  5.0000000e+02,
         7.8664982e-01,  5.4800000e+02,  7.2400000e+02,  8.5479528e-01,
         5.7200000e+02,  9.3200000e+02,  8.6326826e-01,  3.7200000e+02,
         2.1200000e+02,  9.0301907e-01,  2.4400000e+02,  2.3600000e+02,
         9.3274993e-01,  1.0800000e+02,  2.2800000e+02,  9.4893259e-01,
         4.2800000e+02,  5.0000000e+02,  7.7029103e-01,  4.1200000e+02,
         7.2400000e+02,  8.6066049e-01,  3.9600000e+02,  9.2400000e+02,
         8.7252277e-01,  4.6000000e+02,  7.6000000e+01,  7.6979285e-01,
         4.9200000e+02,  7.6000000e+01,  7.8465724e-01,  4.2800000e+02,
         1.1600000e+02,  7.2674561e-01,  5.0800000e+02,  1.16000

In [8]:
output_2d[0]

array([ 4.6800000e+02,  2.0400000e+02,  9.4679272e-01,  4.6800000e+02,
        8.4000000e+01,  7.9522622e-01, -1.0000000e+00, -1.0000000e+00,
       -1.0000000e+00,  5.5600000e+02,  2.0400000e+02,  9.0535182e-01,
        6.9200000e+02,  2.3600000e+02,  9.7329307e-01,  8.2000000e+02,
        2.1200000e+02,  9.2068040e-01,  5.3200000e+02,  5.0000000e+02,
        7.8664982e-01,  5.4800000e+02,  7.2400000e+02,  8.5479528e-01,
        5.7200000e+02,  9.3200000e+02,  8.6326826e-01,  3.7200000e+02,
        2.1200000e+02,  9.0301907e-01,  2.4400000e+02,  2.3600000e+02,
        9.3274993e-01,  1.0800000e+02,  2.2800000e+02,  9.4893259e-01,
        4.2800000e+02,  5.0000000e+02,  7.7029103e-01,  4.1200000e+02,
        7.2400000e+02,  8.6066049e-01,  3.9600000e+02,  9.2400000e+02,
        8.7252277e-01,  4.6000000e+02,  7.6000000e+01,  7.6979285e-01,
        4.9200000e+02,  7.6000000e+01,  7.8465724e-01,  4.2800000e+02,
        1.1600000e+02,  7.2674561e-01,  5.0800000e+02,  1.1600000e+02,
      

In [9]:
output_2d[0][0:-1]

array([ 4.6800000e+02,  2.0400000e+02,  9.4679272e-01,  4.6800000e+02,
        8.4000000e+01,  7.9522622e-01, -1.0000000e+00, -1.0000000e+00,
       -1.0000000e+00,  5.5600000e+02,  2.0400000e+02,  9.0535182e-01,
        6.9200000e+02,  2.3600000e+02,  9.7329307e-01,  8.2000000e+02,
        2.1200000e+02,  9.2068040e-01,  5.3200000e+02,  5.0000000e+02,
        7.8664982e-01,  5.4800000e+02,  7.2400000e+02,  8.5479528e-01,
        5.7200000e+02,  9.3200000e+02,  8.6326826e-01,  3.7200000e+02,
        2.1200000e+02,  9.0301907e-01,  2.4400000e+02,  2.3600000e+02,
        9.3274993e-01,  1.0800000e+02,  2.2800000e+02,  9.4893259e-01,
        4.2800000e+02,  5.0000000e+02,  7.7029103e-01,  4.1200000e+02,
        7.2400000e+02,  8.6066049e-01,  3.9600000e+02,  9.2400000e+02,
        8.7252277e-01,  4.6000000e+02,  7.6000000e+01,  7.6979285e-01,
        4.9200000e+02,  7.6000000e+01,  7.8465724e-01,  4.2800000e+02,
        1.1600000e+02,  7.2674561e-01,  5.0800000e+02,  1.1600000e+02,
      

In [10]:
# In this step each row represents (X, Y, probability)
# if there is no data found probability == -1 
# You can see it for body center at index 2

output_2d[0][0:-1].reshape((-1, 3))

array([[ 4.6800000e+02,  2.0400000e+02,  9.4679272e-01],
       [ 4.6800000e+02,  8.4000000e+01,  7.9522622e-01],
       [-1.0000000e+00, -1.0000000e+00, -1.0000000e+00],
       [ 5.5600000e+02,  2.0400000e+02,  9.0535182e-01],
       [ 6.9200000e+02,  2.3600000e+02,  9.7329307e-01],
       [ 8.2000000e+02,  2.1200000e+02,  9.2068040e-01],
       [ 5.3200000e+02,  5.0000000e+02,  7.8664982e-01],
       [ 5.4800000e+02,  7.2400000e+02,  8.5479528e-01],
       [ 5.7200000e+02,  9.3200000e+02,  8.6326826e-01],
       [ 3.7200000e+02,  2.1200000e+02,  9.0301907e-01],
       [ 2.4400000e+02,  2.3600000e+02,  9.3274993e-01],
       [ 1.0800000e+02,  2.2800000e+02,  9.4893259e-01],
       [ 4.2800000e+02,  5.0000000e+02,  7.7029103e-01],
       [ 4.1200000e+02,  7.2400000e+02,  8.6066049e-01],
       [ 3.9600000e+02,  9.2400000e+02,  8.7252277e-01],
       [ 4.6000000e+02,  7.6000000e+01,  7.6979285e-01],
       [ 4.9200000e+02,  7.6000000e+01,  7.8465724e-01],
       [ 4.2800000e+02,  1.1600

In [7]:
# First array includes X values
# Second array includes Y values
# Third array includes Probablity values
np.array(output_2d[0][0:-1]).reshape((-1, 3)).transpose()

array([[ 4.6800000e+02,  4.6800000e+02, -1.0000000e+00,  5.5600000e+02,
         6.9200000e+02,  8.2000000e+02,  5.3200000e+02,  5.4800000e+02,
         5.7200000e+02,  3.7200000e+02,  2.4400000e+02,  1.0800000e+02,
         4.2800000e+02,  4.1200000e+02,  3.9600000e+02,  4.6000000e+02,
         4.9200000e+02,  4.2800000e+02,  5.0800000e+02],
       [ 2.0400000e+02,  8.4000000e+01, -1.0000000e+00,  2.0400000e+02,
         2.3600000e+02,  2.1200000e+02,  5.0000000e+02,  7.2400000e+02,
         9.3200000e+02,  2.1200000e+02,  2.3600000e+02,  2.2800000e+02,
         5.0000000e+02,  7.2400000e+02,  9.2400000e+02,  7.6000000e+01,
         7.6000000e+01,  1.1600000e+02,  1.1600000e+02],
       [ 9.4679272e-01,  7.9522622e-01, -1.0000000e+00,  9.0535182e-01,
         9.7329307e-01,  9.2068040e-01,  7.8664982e-01,  8.5479528e-01,
         8.6326826e-01,  9.0301907e-01,  9.3274993e-01,  9.4893259e-01,
         7.7029103e-01,  8.6066049e-01,  8.7252277e-01,  7.6979285e-01,
         7.8465724e-01

In [18]:
output_3d.shape

(1, 76)

In [13]:
output_3d[0]

array([  1.7042829 , -48.80735   , 117.6024    ,   0.9467927 ,
         1.6428919 , -64.92284   , 103.97016   ,   0.7952262 ,
         2.6514637 ,   0.4538461 , 123.68647   ,  -1.        ,
        14.399295  , -51.475468  , 124.7803    ,   0.9053518 ,
        38.083683  , -40.8102    , 124.079     ,   0.97329307,
        58.474243  , -45.775066  , 110.81941   ,   0.9206804 ,
         8.101814  ,  -1.6204299 , 131.71086   ,   0.7866498 ,
        12.644009  ,  33.131016  , 143.01453   ,   0.8547953 ,
        18.135437  ,  67.72632   , 157.54741   ,   0.86326826,
        -9.098     , -49.782078  , 116.98078   ,   0.9030191 ,
       -35.90142   , -44.803444  , 121.69339   ,   0.9327499 ,
       -48.46699   , -54.038162  , 118.40572   ,   0.9489326 ,
       -10.999873  ,  -1.6697692 , 131.37958   ,   0.77029103,
       -12.438702  ,  33.04743   , 140.95082   ,   0.8606605 ,
       -12.462727  ,  67.656525  , 157.04054   ,   0.8725228 ,
         1.4587829 , -65.916626  , 104.7222    ,   0.76

In [19]:
# Same structure [X, Y, Z, proba]

output_3d[0].reshape((-1, 4))

array([[  1.7042829 , -48.80735   , 117.6024    ,   0.9467927 ],
       [  1.6428919 , -64.92284   , 103.97016   ,   0.7952262 ],
       [  2.6514637 ,   0.4538461 , 123.68647   ,  -1.        ],
       [ 14.399295  , -51.475468  , 124.7803    ,   0.9053518 ],
       [ 38.083683  , -40.8102    , 124.079     ,   0.97329307],
       [ 58.474243  , -45.775066  , 110.81941   ,   0.9206804 ],
       [  8.101814  ,  -1.6204299 , 131.71086   ,   0.7866498 ],
       [ 12.644009  ,  33.131016  , 143.01453   ,   0.8547953 ],
       [ 18.135437  ,  67.72632   , 157.54741   ,   0.86326826],
       [ -9.098     , -49.782078  , 116.98078   ,   0.9030191 ],
       [-35.90142   , -44.803444  , 121.69339   ,   0.9327499 ],
       [-48.46699   , -54.038162  , 118.40572   ,   0.9489326 ],
       [-10.999873  ,  -1.6697692 , 131.37958   ,   0.77029103],
       [-12.438702  ,  33.04743   , 140.95082   ,   0.8606605 ],
       [-12.462727  ,  67.656525  , 157.04054   ,   0.8725228 ],
       [  1.4587829 , -65

In [16]:
# First array includes X values
# Second array includes Y values
# Third array includes Z values
# Fourth array includes Proba values 

output_3d[0].reshape((-1, 4)).transpose()

array([[  1.7042829 ,   1.6428919 ,   2.6514637 ,  14.399295  ,
         38.083683  ,  58.474243  ,   8.101814  ,  12.644009  ,
         18.135437  ,  -9.098     , -35.90142   , -48.46699   ,
        -10.999873  , -12.438702  , -12.462727  ,   1.4587829 ,
          6.3915153 ,  -2.1604683 ,  -5.3676915 ],
       [-48.80735   , -64.92284   ,   0.4538461 , -51.475468  ,
        -40.8102    , -45.775066  ,  -1.6204299 ,  33.131016  ,
         67.72632   , -49.782078  , -44.803444  , -54.038162  ,
         -1.6697692 ,  33.04743   ,  67.656525  , -65.916626  ,
        -63.372826  , -66.964226  , -64.07578   ],
       [117.6024    , 103.97016   , 123.68647   , 124.7803    ,
        124.079     , 110.81941   , 131.71086   , 143.01453   ,
        157.54741   , 116.98078   , 121.69339   , 118.40572   ,
        131.37958   , 140.95082   , 157.04054   , 104.7222    ,
        113.84957   , 106.374374  , 111.86209   ],
       [  0.9467927 ,   0.7952262 ,  -1.        ,   0.9053518 ,
          0.973